baseURL = 'https://clg3227783168.github.io/'
defaultContentLanguage = "zh-cn"
theme = "hugo-theme-stack"

[languages]
  [languages.zh-cn]
    languageCode = "zh-CN"
    languageName = "简体中文"
    title = "Leo Chen's Site"
    weight = 1

  [languages.zh-cn.params]
    customCSS = ["css/zh-fonts.css"]

  [languages.en]
    languageCode = "en"
    languageName = "English"
    title = "Leo Chen's Site"
    weight = 2

  [languages.en.params]
    customCSS = ["css/en-fonts.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    [params.sidebar]
        [params.sidebar.avatar]
            enabled = true
            local = false
            src = "/avatar.png"

[[languages.zh-cn.menu.main]]
    name = "灵感"
    url = "/inspiration/"
    weight = 10

[[languages.zh-cn.menu.main]]
    name = "待办"
    url = "/todo/"
    weight = 20

[[languages.zh-cn.menu.main]]
    name = "解决方案"
    url = "/solution/"
    weight = 30

[[languages.en.menu.main]]
    name = "Inspiration"
    url = "/en/inspiration/"
    weight = 10

[[languages.en.menu.main]]
    name = "Todo"
    url = "/en/todo/"
    weight = 20

[[languages.en.menu.main]]
    name = "Solution"
    url = "/en/solution/"
    weight = 30

[[params.widgets.page]]
    type = "categories"

[[params.widgets.page]]
    type = "tag-cloud"

[params.comments]
    enabled = true
    provider = "giscus"

    [params.comments.giscus]
        repo = "clg3227783168/clg3227783168"
        repoID = "R_kgDOPucJRQ"
        category = "Announcements"
        categoryID = "DIC_kwDOPucJRc4CvdXu"
        mapping = "url"
        strict = "0"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top"
        lang = "zh-CN"
        theme = "preferred_color_scheme"
